<product_price>
	<product_id>{$Object.product_id}</product_id>
	<product_price_id>{$Object.product_price_id}</product_price_id>
	<product_price>{$Object.product_price}</product_price>
	<product_price_ca>{$Object.product_price_ca}</product_price_ca>
	<product_bonus_point_required>{$Object.product_bonus_point_required}</product_bonus_point_required>
	<product_bonus_point_amount>{$Object.product_bonus_point_amount}</product_bonus_point_amount>
	<discount_type>{$Object.discount_type}</discount_type>
	<discount1_off_p>{$Object.discount1_off_p}</discount1_off_p>
	<discount2_amount>{$Object.discount2_amount}</discount2_amount>
	<discount2_price>{$Object.discount2_price}</discount2_price>
	<discount2_price_ca>{$Object.discount2_price_ca}</discount2_price_ca>
	<discount3_buy_amount>{$Object.discount3_buy_amount}</discount3_buy_amount>
	<discount3_free_amount>{$Object.discount3_free_amount}</discount3_free_amount>
	<product_price_level_list>{$ProductPriceLevelListXML}</product_price_level_list>
</product_price>