<user_balance_transaction>
	<user_balance_id>{$Object.user_balance_id}</user_balance_id>
	<myorder_id>{$Object.myorder_id}</myorder_id>
	<order_no>{$Object.order_no}</order_no>	
	<user_balance_previous>{$Object.user_balance_previous}</user_balance_previous>
	<user_balance_after>{$Object.user_balance_after}</user_balance_after>
	<user_balance_transaction_amount>{$Object.user_balance_transaction_amount}</user_balance_transaction_amount>
	<user_balance_transaction_type>{$Object.user_balance_transaction_type}</user_balance_transaction_type>
	<create_date>{$Object.create_date}</create_date>
	<user_balance_remark>{$Object.user_balance_remark}</user_balance_remark>
	<reference_1>{$Object.reference_1}</reference_1>
	<reference_2>{$Object.reference_2}</reference_2>
	<reference_3>{$Object.reference_3}</reference_3>
</user_balance_transaction>