<user_bonus_point>
	<user_bonus_point_id>{$Object.user_bonus_point_id}</user_bonus_point_id>
	<myorder_id>{$Object.myorder_id}</myorder_id>
	<user_id>{$Object.user_id}</user_id>
	<bonus_point_earned>{$Object.bonus_point_earned}</bonus_point_earned>
	<bonus_point_used>{$Object.bonus_point_used}</bonus_point_used>
	<bonus_point_spent>{$Object.bonus_point_spent}</bonus_point_spent>
	<earn_type>{$Object.earn_type|myxml}</earn_type>
	<create_date>{$Object.create_date|myxml}</create_date>
	<expiry_date>{$Object.expiry_date|myxml}</expiry_date>
	<is_expired>{$Object.is_expired|myxml}</is_expired>
	<is_auto_expire_transaction>{$Object.is_auto_expire_transaction}</is_auto_expire_transaction>
	<effective_bonus_point>{$Object.effective_bonus_point|myxml}</effective_bonus_point>
	<display_bonus_point>{$Object.display_bonus_point}</display_bonus_point>
	<bonus_point_reason>{$Object.bonus_point_reason}</bonus_point_reason>
</user_bonus_point>